#!/bin/sh
# The xinit program allows a user to manually start an Xorg display server.
# The startx(1) script is a front-end for xinit(1).

# Note: Display managers start Xorg for you and generally source xprofile.

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi
exec $1

# source .Xresources file
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

#xrandr --dpi 125.37
#xbacklight -set 30
#exec dwm
#exec startxfce4
